config/routes.rb
Rails.application.routes.draw do
  resources :charge_codes_statistics

  root 'charge_codes_statistics#index'

end

app/models/charge_codes_statistic.rb
class ChargeCodesStatistic < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charge_codes_statistics_controller.rb
class ChargeCodesStatisticsController < ApplicationController
  before_action :set_charge_codes_statistic, only: [:show, :edit, :update, :destroy]

  # GET /charge_codes_statistics
  # GET /charge_codes_statistics.json
  def index
    @charge_codes_statistics = ChargeCodesStatistic.order('created_at DESC').page(params[:page]).per(15)
    # @charge_codes_statistics = ChargeCodesStatistic.all
  end

  # GET /charge_codes_statistics/1
  # GET /charge_codes_statistics/1.json
  def show
  end

  # GET /charge_codes_statistics/new
  def new
    @charge_codes_statistic = ChargeCodesStatistic.new
  end

  # GET /charge_codes_statistics/1/edit
  def edit
  end

  # POST /charge_codes_statistics
  # POST /charge_codes_statistics.json
  def create
    @charge_codes_statistic = ChargeCodesStatistic.new(charge_codes_statistic_params)

    respond_to do |format|
      if @charge_codes_statistic.save
        format.html { redirect_to @charge_codes_statistic, notice: 'Charge codes statistic was successfully created.' }
        format.json { render :show, status: :created, location: @charge_codes_statistic }
      else
        format.html { render :new }
        format.json { render json: @charge_codes_statistic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /charge_codes_statistics/1
  # PATCH/PUT /charge_codes_statistics/1.json
  def update
    respond_to do |format|
      if @charge_codes_statistic.update(charge_codes_statistic_params)
        format.html { redirect_to @charge_codes_statistic, notice: 'Charge codes statistic was successfully updated.' }
        format.json { render :show, status: :ok, location: @charge_codes_statistic }
      else
        format.html { render :edit }
        format.json { render json: @charge_codes_statistic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /charge_codes_statistics/1
  # DELETE /charge_codes_statistics/1.json
  def destroy
    @charge_codes_statistic.destroy
    respond_to do |format|
      format.html { redirect_to charge_codes_statistics_url, notice: 'Charge codes statistic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_charge_codes_statistic
      @charge_codes_statistic = ChargeCodesStatistic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def charge_codes_statistic_params
      params.require(:charge_codes_statistic).permit(:charge_code_id, :charge_code_amount, :charge_code_name, :charge_code_dest_number, :charge_code_instruc_t, :charge_code_instruc_no_t, :yewucode_name, :union_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charge_codes_statistics_helper.rb
module ChargeCodesStatisticsHelper
end

app/views/charge_codes_statistics/_form.html.erb
<%= form_for(@charge_codes_statistic) do |f| %>
  <% if @charge_codes_statistic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@charge_codes_statistic.errors.count, "error") %> prohibited this charge_codes_statistic from being saved:</h2>

      <ul>
      <% @charge_codes_statistic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :charge_code_id %><br>
    <%= f.number_field :charge_code_id %>
  </div>
  <div class="field">
    <%= f.label :charge_code_amount %><br>
    <%= f.number_field :charge_code_amount %>
  </div>
  <div class="field">
    <%= f.label :charge_code_name %><br>
    <%= f.text_field :charge_code_name %>
  </div>
  <div class="field">
    <%= f.label :charge_code_dest_number %><br>
    <%= f.text_field :charge_code_dest_number %>
  </div>
  <div class="field">
    <%= f.label :charge_code_instruc_t %><br>
    <%= f.text_field :charge_code_instruc_t %>
  </div>
  <div class="field">
    <%= f.label :charge_code_instruc_no_t %><br>
    <%= f.text_field :charge_code_instruc_no_t %>
  </div>
  <div class="field">
    <%= f.label :yewucode_name %><br>
    <%= f.text_field :yewucode_name %>
  </div>
  <div class="field">
    <%= f.label :union_name %><br>
    <%= f.text_field :union_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/charge_codes_statistics/edit.html.erb
<h1>Editing Charge Codes Statistic</h1>

<%= render 'form' %>

<%= link_to 'Show', @charge_codes_statistic %> |
<%= link_to 'Back', charge_codes_statistics_path %>

app/views/charge_codes_statistics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Charge Codes Statistics</h1>
<%= paginate(@charge_codes_statistics) %>
<table border="2" >
  <thead>
    <tr>
      <th>Charge code</th>
      <th>Charge code amount</th>
      <th>Charge code name</th>
      <th>Charge code dest number</th>
      <th>Charge code instruc t</th>
      <th>Charge code instruc no t</th>
      <th>Yewucode name</th>
      <th>Union name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @charge_codes_statistics.each do |charge_codes_statistic| %>
    <tr>
      <td><%= charge_codes_statistic.charge_code_id %></td>
      <td><%= charge_codes_statistic.charge_code_amount %></td>
      <td><%= charge_codes_statistic.charge_code_dest_number %></td>
      <td><%= charge_codes_statistic.charge_code_instruc_t %></td>
      <td><%= charge_codes_statistic.charge_code_instruc_no_t %></td>
      <td><%= charge_codes_statistic.charge_code_name %></td>
      <td><%= charge_codes_statistic.yewucode_name %></td>
      <td><%= charge_codes_statistic.union_name %></td>
      <td bgcolor="green"><button type="button"><%= link_to 'Show', charge_codes_statistic %></button></td>
      <td bgcolor="green"><button type="button"><%= link_to 'Edit', edit_charge_codes_statistic_path(charge_codes_statistic) %></button></td>
      <td bgcolor="green"><button type="button"><%= link_to 'Destroy', charge_codes_statistic, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
    </tr>
    <% end %>
  </tbody>

</table>
<h1><button type="button" style="background: green"><%= link_to 'New Charge codes statistic', new_charge_codes_statistic_path %></button></h1>
<%= paginate(@charge_codes_statistics) %>
<br>

app/views/charge_codes_statistics/new.html.erb
<h1>New Charge Codes Statistic</h1>

<%= render 'form' %>

<%= link_to 'Back', charge_codes_statistics_path %>

app/views/charge_codes_statistics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Charge code:</strong>
  <%= @charge_codes_statistic.charge_code_id %>
</p>

<p>
  <strong>Charge code amount:</strong>
  <%= @charge_codes_statistic.charge_code_amount %>
</p>

<p>
  <strong>Charge code name:</strong>
  <%= @charge_codes_statistic.charge_code_name %>
</p>

<p>
  <strong>Charge code dest number:</strong>
  <%= @charge_codes_statistic.charge_code_dest_number %>
</p>

<p>
  <strong>Charge code instruc t:</strong>
  <%= @charge_codes_statistic.charge_code_instruc_t %>
</p>

<p>
  <strong>Charge code instruc no t:</strong>
  <%= @charge_codes_statistic.charge_code_instruc_no_t %>
</p>

<p>
  <strong>Yewucode name:</strong>
  <%= @charge_codes_statistic.yewucode_name %>
</p>

<p>
  <strong>Union name:</strong>
  <%= @charge_codes_statistic.union_name %>
</p>

<%= link_to 'Edit', edit_charge_codes_statistic_path(@charge_codes_statistic) %> |
<%= link_to 'Back', charge_codes_statistics_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fufeimaguanli</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>